"""Independent deterministic fixtures for sequential-analysis tests."""

from __future__ import annotations

from datetime import UTC, datetime

from packages.experiments.analysis import (
    AnalysisUnit,
    EstimandDefinition,
    EstimandKind,
    MetricType,
    RandomizedAnalysisMethod,
    SampleCounts,
)
from packages.experiments.analysis.randomized.sequential import (
    SequentialAnalysisPlan,
    SequentialLookDefinition,
)
from tests.analysis_contract_fixtures import randomized_request, source

# Independently evaluated from A(t)=2*Phi_bar(Phi^-1(.975)/sqrt(t)), not generated by
# packages.experiments.analysis.randomized.sequential.boundaries.
FOUR_LOOK_REFERENCE = (
    (1, 0.25, 0.00008857543832140365, 0.00008857543832140365, 3.919927969080109),
    (2, 0.50, 0.005574596680784402, 0.005486021242462998, 2.7770175753094137),
    (3, 0.75, 0.023625121317601142, 0.01805052463681674, 2.3645800769988976),
    (4, 1.00, 0.05, 0.02637487868239886, 2.220647016435692),
)


def sequential_plan(
    *,
    information_times: tuple[float, ...] = (0.25, 0.5, 0.75, 1.0),
    total_alpha: float = 0.05,
    metric_type: MetricType = MetricType.CONTINUOUS,
    expected_cumulative_sample_counts: tuple[SampleCounts, ...] | None = None,
) -> SequentialAnalysisPlan:
    request = randomized_request()
    analysis_unit = AnalysisUnit(unit_id="account", label="Account")
    outcome = request.outcome.model_copy(
        update={"metric": request.outcome.metric.model_copy(update={"metric_type": metric_type})}
    )
    estimand = (
        EstimandKind.DIFFERENCE_IN_PROPORTIONS
        if metric_type is MetricType.BINARY
        else EstimandKind.DIFFERENCE_IN_MEANS
    )
    request = request.model_copy(
        update={
            "outcome": outcome,
            "estimand": EstimandDefinition(kind=estimand),
            "study_design": request.study_design.model_copy(
                update={"method": RandomizedAnalysisMethod.SEQUENTIAL_AB}
            ),
            "unit_of_analysis": analysis_unit,
            "sample_counts": SampleCounts(total=60, treatment=30, control=30),
        }
    )
    return SequentialAnalysisPlan(
        plan_id="issue-94-primary",
        experiment_id="payment-ranking-2026-07",
        analysis_request=request,
        total_alpha=total_alpha,
        planned_looks=tuple(
            SequentialLookDefinition(
                look_index=index,
                information_time=time,
                expected_cumulative_sample_counts=(
                    expected_cumulative_sample_counts[index - 1]
                    if expected_cumulative_sample_counts is not None
                    else None
                ),
            )
            for index, time in enumerate(information_times, start=1)
        ),
        registration_marker="registry-entry-94-v1",
        registered_at=datetime(2026, 7, 1, tzinfo=UTC),
        provenance=(source(),),
    )


__all__ = ["FOUR_LOOK_REFERENCE", "sequential_plan"]
